version: '3.8'
services:
  postgres:
    image: postgres:14.7
    container_name: postgres
    restart: always
    networks:
      - forem-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:7.16.3
    container_name: elasticsearch
    user: root
    networks:
      - forem-network
    environment:
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - ELASTIC_USERNAME=${ELK_ROOT_USER}
      - ELASTIC_PASSWORD=${ELK_ROOT_PASSWORD}
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=${LICENSE}
      - xpack.monitoring.enabled = false
      - xpack.graph.enabled = false
      - xpack.watcher.enabled = false
      - bootstrap.memory_lock = true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - ${ES_PORT}:9200
    volumes:
      - ./volumes/esdata:/usr/share/elasticsearch/data

  redis:
    image: redis:6-alpine
    restart: always
    container_name: redis
    command: redis-server --requirepass $REDIS_PASSWORD --appendonly yes
    networks:
      - forem-network
    volumes:
      - ./volumes/redis:/data:rw,z
    ports:
      - '6379:6379'

  forem:
    image: quay.io/forem/forem:latest
    environment:
      # Rails-specific stuff
      RAILS_ENV: ${RAILS_ENV}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_SERVE_STATIC_FILES: ${RAILS_SERVE_STATIC_FILES}
      RAILS_LOG_TO_STDOUT: ${RAILS_LOG_TO_STDOUT}
      RAILS_MAX_THREADS: ${RAILS_MAX_THREADS}
      LOG_LEVEL: ${LOG_LEVEL}
      WEB_CONCURRENCY: ${WEB_CONCURRENCY}
      # Forem-specific stuff
      APP_PROTOCOL: ${APP_PROTOCOL}
      APP_DOMAIN: ${APP_DOMAIN}
      COMMUNITY_NAME: ${COMMUNITY_NAME}
      FOREM_CREATOR_SECRET: ${FOREM_CREATOR_SECRET}
      AWS_ID: ${AWS_ID}
      AWS_SECRET: ${AWS_SECRET}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_UPLOAD_REGION: ${AWS_UPLOAD_REGION}


  # Docker Networks
networks:
  # All container connect in a network
  forem-network:
    driver: bridge

volumes:
  esdata:
  redis:
